language: go

go:
  - 1.8
  - 1.9
  - '1.10'
  - '1.11'
  - '1.12'
  - tip
  - master

go_import_path: stash.kopano.io/kc/libkcoidc

matrix:
  allow_failures:
    - go: tip master
  fast_finish: true

before_install:
  - DEP_RELEASE_TAG=v0.5.0
  - mkdir -p $HOME/bin
  - curl -sSL -o $HOME/dep https://github.com/golang/dep/releases/download/$DEP_RELEASE_TAG/dep-linux-amd64 && chmod 755 $HOME/dep
  - export PATH="$HOME/bin:$PATH"

script:
  - ./bootstrap.sh
  - ./configure
  - make
  - make examples
