language: go

go:
  - '1.11'
  - '1.12'
  - '1.13'
  - tip
  - master

go_import_path: stash.kopano.io/kc/libkcoidc

matrix:
  allow_failures:
    - go: tip master
  fast_finish: true

script:
  - ./bootstrap.sh
  - ./configure
  - make
  - make examples
