# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "~3.1.0"

[[constraint]]
  name = "stash.kopano.io/kgol/oidc-go"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
